stages:          # List of stages for jobs, and their order of execution
  - test

test-job:  
  image: cypress/browsers:node-20.14.0-chrome-125.0.6422.141-1-ff-126.0.1-edge-125.0.2535.85-1       #run chome docker image
  stage: test   
  script:
    - npm ci
    - npm run run-chrome

